name: MSBuild

on:
  pull_request:

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  tag_name: '0.0.0.${{ github.run_number }}'

permissions:
  contents: read

jobs:

  check-commit:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: read
    outputs:
      commit_message: ${{ steps.get-commit-message.outputs.LAST_MSG }}
    
    steps:
    - id: get-commit-message
      name: Get commits
      env:
        COMMITS_URL: ${{ github.event.pull_request.commits_url }}
      run: |
        if [ "${COMMITS_URL}x" != "x" ]; then
          LAST_MSG=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${COMMITS_URL}?per_page=100" | jq -r .[-1].commit.message)
          echo "LAST_MSG<<EOF" >> "$GITHUB_OUTPUT"
          echo "$LAST_MSG" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
        else
          echo 'LAST_MSG=' >> "$GITHUB_OUTPUT"
        fi

  build:
    runs-on: windows-latest
    needs: check-commit
    strategy:
      fail-fast: true
    outputs:
      version: ${{ steps.get-variables.outputs.version }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        fetch-depth: 1

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - id: cache-nuget
      uses: actions/cache@v3
      with:
        path: |
            ~/.nuget/packages
            packages
            SentryDotnetDiagnostics/obj/SentryDotnetDiagnostics.csproj.nuget.*
            SentryDotnetDiagnostics/obj/project.*
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/SentryDotnetDiagnostics.csproj') }}
        
    - name: Restore NuGet packages
      if: steps.cache-nuget.outputs.cache-hit != 'true'
      working-directory: ${{ github.workspace }}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - id: get-variables
      name: Make Variables
      working-directory: ${{ github.workspace }}/SentryDotnetDiagnostics
      run: |
        $VERSION = Select-String -Path "Properties\AssemblyInfo.cs" -Pattern '^\[assembly: AssemblyVersion\(\"(.+)\"\)\]$' | select -expand Matches | foreach {$_.groups[1].value}
        echo "version=$VERSION" >> $env:GITHUB_OUTPUT

    - name: Build
      working-directory: ${{ github.workspace }}
      run: |
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: NuGet Upload
      if: ${{ contains(needs.check-commit.outputs.commit_message, '[ci release]') }}
      working-directory: ${{ github.workspace }}/SentryDotnetDiagnostics
      run: |
        nuget setApiKey ${{ secrets.NUGET }}
        nuget pack
        nuget push DiagnosticsExtensions.Sentry.${{ steps.get-variables.outputs.version }}.nupkg -Source https://api.nuget.org/v3/index.json
